[package]
name = "fuzzyblue"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
ash = "0.29.0"
vk-shader-macros = "0.2"
